IOM-9761: fixed search for jq, fix for pod search in progess

diff --git a/templates/devenv-cli.sh.template b/templates/devenv-cli.sh.template
--- a/templates/devenv-cli.sh.template
+++ b/templates/devenv-cli.sh.template
@@ -1669,6 +1669,63 @@ kube_resource_exists() (
     [ "$RESOURCE_EXISTS" = 'true' ]
 )
 
+#-------------------------------------------------------------------------------
+# $1: timestamp
+# ->  seconds
+#-------------------------------------------------------------------------------
+time2seconds() {
+    if [ "$(OS)" = 'Darwin' ]; then
+        date -j -f '%Y-%m-%dT%H:%M:%S' "$1" '+%s'
+    else
+        date -d "$1" '+%s'
+    fi
+}
+
+#-------------------------------------------------------------------------------
+# get id of pod matching requested app-name
+# if there is more than one pod matching (e.g. one is terminating, one is
+# starting), the "running" pod is returned. If no such exists, the newer one
+# will be selected.
+# $1: app-name
+# -> pod-name or empty, if no matching pod exists
+#-------------------------------------------------------------------------------
+kube_get_pod() (
+    # get name, status and creation timestamp of pods and store them in an array
+    # the array is flat and contains all names, statuses and timestamps in this order
+    POD_INFO=( $(kubectl get pods --namespace $EnvId -l app=$APP_NAME -o jsonpath='{.items[*].metadata.name} {.items[*].status.phase} {.items[*].metadata.creationTimestamp}' 2> /dev/null) )
+
+    POD_COUNT=$(expr ${#POD_INFO[@]} / 3)
+    POD_NAME=''
+
+    # search for a pod in state running and store its name
+    I=0
+    while [ -z "$POD_NAME" -a "$I" -lt "$POD_COUNT" ]; do
+        NAME_INDEX=$(expr $I * 3 + 0)
+        STATUS_INDEX=$(expr $I * 3 + 1)
+        if [ "${POD_INFO[$STATUS_INDEX]}" = 'Running' ]; then
+            POD_NAME="${POD_INFO[$NAME_INDEX]}"
+        fi
+        I=$(expr $I + 1)
+    done
+
+    # search for the newest pod and store its name
+    I=0
+    POD_SECONDS=
+    while [ -z "$POD_NAME" -a "$I" -lt "$POD_COUNT" ]; do
+        NAME_INDEX=$(expr $I * 3 + 0)
+        TIMESTAMP_INDEX=$(expr $I * 3 + 2)
+        if [ -z "$POD_SECONDS" ]; then
+            POD_SECONDS="$(time2seconds "${POD_INFO[$TIMESTAMP_INDEX]}")"
+            POD_NAME="${POD_INFO[$NAME_INDEX]}"
+        elif [ "$(time2seconds "${POD_INFO[$TIMESTAMP_INDEX]}")" -gt "$POD_SECONDS" ]; then
+            POD_SECONDS="$(time2seconds "${POD_INFO[$TIMESTAMP_INDEX]}")"
+            POD_NAME="${POD_INFO[$NAME_INDEX]}"
+        fi
+    done
+    
+    echo "$POD_NAME"
+)
+
 ################################################################################
 # functions, implementing the info handlers
 ################################################################################
@@ -2892,6 +2949,24 @@ level_filter() {
 }
 
 #-------------------------------------------------------------------------------
+# helper to find out, if jq is available
+# -> true|false
+#-------------------------------------------------------------------------------
+jq_exists() {
+    if [ ! -z "$(which jq)" ]; then
+        true
+    else
+        alias | while read IGNORE ALIAS; do
+            if echo "$ALIAS" | grep -q '^jq='; then
+                true
+                break
+            fi
+            false
+        done
+    fi
+}
+
+#-------------------------------------------------------------------------------
 # get logs of dbaccount init container
 # $1|2: [FATAL|ERROR|WARN|INFO|DEBUG|TRACE], defaults to WARN
 # $1|2: [-f] if set, messages are printed in follow mode
@@ -2919,8 +2994,8 @@ log-dbaccount() {
     if is_in_array "$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')" ${LEVELS[@]}; then
         LEVEL=$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')
 
-        if [ -z "$(which jq)" ]; then
-            log_json ERROR "log-dbaccount: jq not found in PATH" < /dev/null
+        if ! jq_exists; then
+            log_json ERROR "log-dbaccount: jq not found" < /dev/null
             false
         else
             if [ "$FOLLOW" = 'true' ]; then
@@ -2974,8 +3049,8 @@ log-config() {
     if is_in_array "$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')" ${LEVELS[@]}; then
         LEVEL=$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')
 
-        if [ -z "$(which jq)" ]; then
-            log_json ERROR "log-config: jq not found in PATH" < /dev/null
+        if ! jq_exists; then
+            log_json ERROR "log-config: jq not found" < /dev/null
             false
         else
             if [ "$FOLLOW" = 'true' ]; then
@@ -3029,8 +3104,8 @@ log-app() {
     if is_in_array "$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')" ${LEVELS[@]}; then
         LEVEL=$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')
 
-        if [ -z "$(which jq)" ]; then
-            log_json ERROR "log-app: jq not found in PATH" < /dev/null
+        if ! jq_exists; then
+            log_json ERROR "log-app: jq not found" < /dev/null
             false
         else
             if [ "$FOLLOW" = 'true' ]; then
@@ -3085,8 +3160,8 @@ log-access() {
     if is_in_array "$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')" ${LEVELS[@]}; then
         LEVEL=$(echo "$LEVEL" | tr '[a-z]' '[A-Z]')
 
-        if [ -z "$(which jq)" ]; then
-            log_json ERROR "log-app: jq not found in PATH" < /dev/null
+        if ! jq_exists; then
+            log_json ERROR "log-app: jq not found" < /dev/null
             false
         else
             if [ "$FOLLOW" = 'true' ]; then
